### ISSUE TITLE
Additional Info on Supported/Needed CAS Attributes to Return?

### ISSUE THREAD

**Issue by orware** [DSIEtudes/plugin-cas-auth#1]
Thank you Jamaïca (@jamaicv) for putting together this plugin (I'm hoping it'll help make our Kanboard installation SSO-enabled fairly easily!

The main thing I wanted to ask about, either to see what details you could provide, but additionally, to help maybe put this into the documentation as a bit of extra detail, is what attributes (and the names) I should use when passing back values via CAS from my IdP?

In the CasAuthProvider file I see some mention/reference to actual attribute names as I can see here:
```
$this->userInfo = new CasUserProvider(
	$this->service->getAttribute('distinguishedName'),
	$this->service->getAttribute('userprincipalname'),
	$this->service->getAttribute('cn'),
	$this->service->getAttribute('mail'),
	$this->service->getAttribute($this->getRole($this->service->getAttribute('memberof'))),
	$this->service->getAttribute('memberof'),
	$this->service->getAttribute('jpegPhoto'),
	$this->service->getAttribute('')
);
```

But at the moment I'm not 100% sure whether or not I have to send back some or all of these fields from my CAS IdP (I haven't gotten to the stage of actually testing this out, which is part of what I'd be doing next, but figured it wouldn't hurt to ask/mention it in case you had some immediate thoughts you could share).

In particular, I'm interested in how the getRole / memberof part behaves (would it automatically create the needed groups in Kanboard as they come in from CAS? Or would they need to be created beforehand in Kanboard and then if there is a match the user gets added in?)

Also, I'm curious about the "LDAP_GROUP_ADMIN_DN" and "LDAP_GROUP_MANAGER_DN" settings from the Kanboard configuration (I'm currently making use of the first one to assign Admin rights to specific users when they login, but not sure how things will behave after switching to the CAS authentication option...I'm not sure if the user that would normally be an Admin would revert back to being a normal User in this case, or if it would be left alone).

**Comment by orware** [comment]
@jamaicv,

I did spend some time earlier this afternoon running various tests.

I finally got to the point where I started receiving the following error:

```
Fatal error: Uncaught TypeError: 
Argument 1 passed to Kanboard\Plugin\CASAuth\Auth\CasAuthProvider::getRole() must be of the type array, null given, 
called in C:\xampp_7.4.10\htdocs\kanban\plugins\CASAuth\Auth\CasAuthProvider.php on line 75 and 
defined in C:\xampp_7.4.10\htdocs\kanban\plugins\CASAuth\Auth\CasAuthProvider.php:101 
Stack trace: #0 C:\xampp_7.4.10\htdocs\kanban\plugins\CASAuth\Auth\CasAuthProvider.php(75): Kanboard\Plugin\CASAuth\Auth\CasAuthProvider->getRole(NULL) 
#1 C:\xampp_7.4.10\htdocs\kanban\app\Core\Security\AuthenticationManager.php(99): Kanboard\Plugin\CASAuth\Auth\CasAuthProvider->authenticate() 
#2 C:\xampp_7.4.10\htdocs\kanban\app\Middleware\AuthenticationMiddleware.php(36): Kanboard\Core\Security\AuthenticationManager->preAuthentication() 
#3 C:\xampp_7.4.10\htdocs\kanban\app\Middleware\AuthenticationMiddleware.php(28): Kanboard\Middleware\AuthenticationMiddleware->handleAuthentication() 
#4 C:\xampp_7.4.10\htdocs\kanban\app\Core\Controller\BaseMiddleware.php(55): Kanboard\Middleware\AuthenticationM in C:\xampp_7.4.10\htdocs\kanban\plugins\CASAuth\Auth\CasAuthProvider.php on line 101
```

I noticed that you were using the /samlValidate (SAML 1.1 option for the client) so just to test I switched that constant to the CAS v2.0 one to see if that might help.

With that test, it seemed I didn't receive the same error, which seemed like an improvement, however I still wasn't logged in fully (I was redirected to the /login endpoint but wasn't actually logged in successfully).

Not sure if you have any tips that might be useful that I could try (I've already verified that my IdP should be returning all of the needed attributes, which I've named the same as the ones referenced in the code snippet from my initial message earlier above).

**Comment by matgn** [comment]
> @jamaicv,
> 
> I did spend some time earlier this afternoon running various tests.
> 
> I finally got to the point where I started receiving the following error:
> 
> ```
> Fatal error: Uncaught TypeError: 
> Argument 1 passed to Kanboard\Plugin\CASAuth\Auth\CasAuthProvider::getRole() must be of the type array, null given, 
> called in C:\xampp_7.4.10\htdocs\kanban\plugins\CASAuth\Auth\CasAuthProvider.php on line 75 and 
> defined in C:\xampp_7.4.10\htdocs\kanban\plugins\CASAuth\Auth\CasAuthProvider.php:101 
> Stack trace: #0 C:\xampp_7.4.10\htdocs\kanban\plugins\CASAuth\Auth\CasAuthProvider.php(75): Kanboard\Plugin\CASAuth\Auth\CasAuthProvider->getRole(NULL) 
> #1 C:\xampp_7.4.10\htdocs\kanban\app\Core\Security\AuthenticationManager.php(99): Kanboard\Plugin\CASAuth\Auth\CasAuthProvider->authenticate() 
> #2 C:\xampp_7.4.10\htdocs\kanban\app\Middleware\AuthenticationMiddleware.php(36): Kanboard\Core\Security\AuthenticationManager->preAuthentication() 
> #3 C:\xampp_7.4.10\htdocs\kanban\app\Middleware\AuthenticationMiddleware.php(28): Kanboard\Middleware\AuthenticationMiddleware->handleAuthentication() 
> #4 C:\xampp_7.4.10\htdocs\kanban\app\Core\Controller\BaseMiddleware.php(55): Kanboard\Middleware\AuthenticationM in C:\xampp_7.4.10\htdocs\kanban\plugins\CASAuth\Auth\CasAuthProvider.php on line 101
> ```
> 
> I noticed that you were using the /samlValidate (SAML 1.1 option for the client) so just to test I switched that constant to the CAS v2.0 one to see if that might help.
> 
> With that test, it seemed I didn't receive the same error, which seemed like an improvement, however I still wasn't logged in fully (I was redirected to the /login endpoint but wasn't actually logged in successfully).
> 
> Not sure if you have any tips that might be useful that I could try (I've already verified that my IdP should be returning all of the needed attributes, which I've named the same as the ones referenced in the code snippet from my initial message earlier above).

Same problem here ! Did you find a patch ?
